# Generated by Django 2.2.5 on 2019-09-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='speci',
            field=models.CharField(choices=[('狗', '狗'), ('猫', '猫'), ('其他', '其他')], default='狗', max_length=10, verbose_name='物种'),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=6, verbose_name='性别'),
        ),
    ]
