# Generated by Django 2.2.5 on 2019-09-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0003_auto_20190919_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='petimg',
            field=models.CharField(default=1, max_length=50, verbose_name='宠物图片路径'),
            preserve_default=False,
        ),
    ]
