# Generated by Django 2.2.5 on 2019-09-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0004_pets_petimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='petimg',
        ),
    ]
