# Generated by Django 2.2.5 on 2019-09-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0005_remove_pets_petimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='petsex',
            field=models.CharField(choices=[('公', '公'), ('母', '母')], default='公', max_length=6, verbose_name='性别'),
        ),
    ]
