# Generated by Django 2.2.5 on 2019-10-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0006_auto_20190925_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goodtype',
            field=models.CharField(choices=[('宠物食品', '宠物食品'), ('宠物玩具', '宠物玩具'), ('清洁用品', '清洁用品'), ('药品', '药品'), ('宠物衣物', '宠物衣物')], default='宠物食品', max_length=10, verbose_name='商品类型'),
        ),
    ]
