# Generated by Django 2.2.5 on 2019-10-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0008_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='dmentid',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='userid',
        ),
        migrations.DeleteModel(
            name='Developments',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
