# Generated by Django 2.2.5 on 2019-10-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0009_auto_20191011_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developments',
            fields=[
                ('dmentid', models.AutoField(primary_key=True, serialize=False)),
                ('dmenttext', models.TextField(verbose_name='动态详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bysjapp.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '动态',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('dmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bysjapp.Developments', verbose_name='动态')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bysjapp.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
            },
        ),
    ]
