# Generated by Django 2.2.5 on 2019-10-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0010_developments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='developments',
            name='username',
            field=models.CharField(default=111, max_length=20, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
