# Generated by Django 2.2.5 on 2019-10-17 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0012_goods_goodprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oderid', models.CharField(max_length=30, verbose_name='订单号')),
                ('oderitem', models.TextField(verbose_name='订单详情')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('totalprice', models.FloatField(default=0, verbose_name='总价')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bysjapp.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
