# Generated by Django 2.2.5 on 2019-10-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0014_likes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likes',
        ),
        migrations.AddField(
            model_name='developments',
            name='likenum',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
