# Generated by Django 2.2.5 on 2019-10-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0015_auto_20191020_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='head',
            field=models.CharField(default=1, max_length=20, verbose_name='头像'),
            preserve_default=False,
        ),
    ]
