# Generated by Django 2.2.5 on 2019-10-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0016_users_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='head',
            field=models.CharField(default='nohead.png', max_length=20, verbose_name='头像'),
        ),
    ]
