# Generated by Django 2.2.5 on 2019-10-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0017_auto_20191024_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='vnum',
            field=models.IntegerField(default=0, verbose_name='访问人数'),
        ),
    ]
