# Generated by Django 2.2.5 on 2019-10-31 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0018_pets_vnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
