# Generated by Django 2.2.5 on 2019-11-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0019_pets_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='gimg',
            field=models.FileField(default=1, upload_to='', verbose_name='图片'),
            preserve_default=False,
        ),
    ]
