# Generated by Django 2.2.5 on 2020-02-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0020_goods_gimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='gimg',
        ),
    ]
