# Generated by Django 2.2.5 on 2020-02-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0021_remove_goods_gimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default=1, max_length=11, verbose_name='收货电话'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='useradress',
            field=models.CharField(default=1, max_length=35, verbose_name='收货地址'),
            preserve_default=False,
        ),
    ]
