# Generated by Django 2.2.5 on 2020-02-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0023_auto_20200222_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='oders',
            field=models.CharField(choices=[('未发货', '未发货'), ('已发货', '已发货')], default='未发货', max_length=6, verbose_name='状态'),
        ),
    ]
