# Generated by Django 2.2.5 on 2020-03-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0024_orders_oders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('商品', '商品'), ('宠物', '宠物')], default='商品', max_length=6, verbose_name='种类'),
        ),
        migrations.AddField(
            model_name='pets',
            name='petprice',
            field=models.FloatField(default=0, verbose_name='宠物价格'),
        ),
    ]
