# Generated by Django 2.2.5 on 2020-03-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0025_auto_20200310_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='pett',
            field=models.CharField(choices=[('已出售', '已出售'), ('未出售', '未出售')], default='未出售', max_length=6, verbose_name='状态'),
        ),
    ]
