# Generated by Django 2.2.5 on 2020-03-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0026_pets_pett'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bysjapp.Users', verbose_name='关注用户')),
            ],
            options={
                'verbose_name': '关注',
                'verbose_name_plural': '关注',
            },
        ),
    ]
