# Generated by Django 2.2.5 on 2020-04-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0029_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likenum',
        ),
    ]
