# Generated by Django 2.2.5 on 2020-04-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0030_remove_comment_likenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mnum',
            field=models.IntegerField(default=0, verbose_name='消息数'),
        ),
    ]
