# Generated by Django 2.2.5 on 2020-04-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bysjapp', '0032_users_newmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='head',
            field=models.CharField(default='nohead.png', max_length=40, verbose_name='头像'),
        ),
    ]
